name: i18n_omatic
description: A package for managing translations with automatic scanning of source code to find strings to translate.
homepage: https://github.com/jctophefabre/i18n_omatic
issue_tracker: https://github.com/jctophefabre/i18n_omatic/issues

version: 0.1.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  args: ^1.6.0
  glob: ^1.2.0
  yaml: ^2.2.1
  path: ^1.7.0

dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.0